Support custom loader
kirualex/SwiftyGif pull request #129
Opened 2020-02-21 08:22 UTC by bigearsenal

2020-03-01 04:06 UTC, congsun requested changes
I think we should put more thoughts on the customView we can pass in.

I would recommend to have a protocol like 
```swift
protocol CustomLoader {
    func setupConstraints(for superView: UIView)
    func startAnimating()
    func stopAnimating()
}
```
And make `UIActivityIndicatorView` conforms to it. Then on the call site, we can:
- Easily separate code between default loader / custom loader, not have to guess how to setup the constraints, 
- Not need to put the code ` (loader as? UIActivityIndicatorView)?.startAnimating()` <- This will have side effects if the passed in view is a subclass of `UIActivityIndicatorView` and might have a different control flow. In addition, custom loader should still provide similar function and let framework decide when to animate.

2020-03-01 04:06 UTC, congsun commented on SwiftyGif/UIImageView+SwiftyGif.swift
> +        addConstraint(NSLayoutConstraint(
For custom `UIView`, setting `centerX` and `centerY` constraints will normally not satisfy autolayout requirements.

2020-03-01 15:11 UTC, bigearsenal commented
Thanks for your suggestion. I've thought about it before, but I just wrote this code quickly to satisfy my project's requirement without digging into detail.
I just didn't have enough time.
You can contribute to this pull request. I'm highly appreciated

2020-05-20 09:23 UTC, merged

2020-05-20 09:24 UTC, kirualex commented
Thanks for your work @bigearsenal

2020-05-26 08:32 UTC, bigearsenal commented
You're welcome! Thanks for awesome library :D